// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: ranking.proto

// RankingService: feed-aggregation-service (Go) -> ranking-service (Rust).
// Composite scoring for a batch of feed candidates. Internal only --
// bypasses the Envoy gateway (see doc/gateway.md).
//
// Deliberately layered wire format: gRPC provides the typed RPC contract,
// connection multiplexing (HTTP/2), and streaming readiness, but the
// message body is a raw FlatBuffers buffer (schemas/fbs/ranking.fbs), not
// a nested protobuf message. This is a specific, narrow choice for this
// one high-volume, list-heavy call: Protobuf's own wire format still
// requires a full parse+allocate pass to materialize a message, where
// FlatBuffers gives zero-copy random access straight into the received
// bytes. gRPC's typed contract is worth keeping (service discovery,
// codegen'd stubs, HTTP/2 transport); its payload codec specifically is
// not, for this call. Full reasoning: doc/wire-protocols.md.

package rankingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FlatBuffers-encoded feed.ranking.CandidateList (schemas/fbs/ranking.fbs).
	CandidatesFb  []byte `protobuf:"bytes,1,opt,name=candidates_fb,json=candidatesFb,proto3" json:"candidates_fb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	mi := &file_ranking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *RankRequest) GetCandidatesFb() []byte {
	if x != nil {
		return x.CandidatesFb
	}
	return nil
}

type RankResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FlatBuffers-encoded feed.ranking.RankedList (schemas/fbs/ranking.fbs).
	RankedFb      []byte `protobuf:"bytes,1,opt,name=ranked_fb,json=rankedFb,proto3" json:"ranked_fb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	mi := &file_ranking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *RankResponse) GetRankedFb() []byte {
	if x != nil {
		return x.RankedFb
	}
	return nil
}

var File_ranking_proto protoreflect.FileDescriptor

const file_ranking_proto_rawDesc = "" +
	"\n" +
	"\rranking.proto\x12\x0ffeed.ranking.v1\"2\n" +
	"\vRankRequest\x12#\n" +
	"\rcandidates_fb\x18\x01 \x01(\fR\fcandidatesFb\"+\n" +
	"\fRankResponse\x12\x1b\n" +
	"\tranked_fb\x18\x01 \x01(\fR\brankedFb2U\n" +
	"\x0eRankingService\x12C\n" +
	"\x04Rank\x12\x1c.feed.ranking.v1.RankRequest\x1a\x1d.feed.ranking.v1.RankResponseB>Z<feed-aggregation-service/internal/genproto/ranking;rankingpbb\x06proto3"

var (
	file_ranking_proto_rawDescOnce sync.Once
	file_ranking_proto_rawDescData []byte
)

func file_ranking_proto_rawDescGZIP() []byte {
	file_ranking_proto_rawDescOnce.Do(func() {
		file_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ranking_proto_rawDesc), len(file_ranking_proto_rawDesc)))
	})
	return file_ranking_proto_rawDescData
}

var file_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ranking_proto_goTypes = []any{
	(*RankRequest)(nil),  // 0: feed.ranking.v1.RankRequest
	(*RankResponse)(nil), // 1: feed.ranking.v1.RankResponse
}
var file_ranking_proto_depIdxs = []int32{
	0, // 0: feed.ranking.v1.RankingService.Rank:input_type -> feed.ranking.v1.RankRequest
	1, // 1: feed.ranking.v1.RankingService.Rank:output_type -> feed.ranking.v1.RankResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ranking_proto_init() }
func file_ranking_proto_init() {
	if File_ranking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ranking_proto_rawDesc), len(file_ranking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ranking_proto_goTypes,
		DependencyIndexes: file_ranking_proto_depIdxs,
		MessageInfos:      file_ranking_proto_msgTypes,
	}.Build()
	File_ranking_proto = out.File
	file_ranking_proto_goTypes = nil
	file_ranking_proto_depIdxs = nil
}
