// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: ranking.proto

// RankingService: feed-aggregation-service (Go) -> ranking-service (Rust).
// Composite scoring for a batch of feed candidates. Internal only --
// bypasses the Envoy gateway (see doc/gateway.md).
//
// Deliberately layered wire format: gRPC provides the typed RPC contract,
// connection multiplexing (HTTP/2), and streaming readiness, but the
// message body is a raw FlatBuffers buffer (schemas/fbs/ranking.fbs), not
// a nested protobuf message. This is a specific, narrow choice for this
// one high-volume, list-heavy call: Protobuf's own wire format still
// requires a full parse+allocate pass to materialize a message, where
// FlatBuffers gives zero-copy random access straight into the received
// bytes. gRPC's typed contract is worth keeping (service discovery,
// codegen'd stubs, HTTP/2 transport); its payload codec specifically is
// not, for this call. Full reasoning: doc/wire-protocols.md.

package rankingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankingService_Rank_FullMethodName = "/feed.ranking.v1.RankingService/Rank"
)

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankingServiceClient interface {
	Rank(ctx context.Context, in *RankRequest, opts ...grpc.CallOption) (*RankResponse, error)
}

type rankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingServiceClient(cc grpc.ClientConnInterface) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) Rank(ctx context.Context, in *RankRequest, opts ...grpc.CallOption) (*RankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankResponse)
	err := c.cc.Invoke(ctx, RankingService_Rank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
// All implementations must embed UnimplementedRankingServiceServer
// for forward compatibility.
type RankingServiceServer interface {
	Rank(context.Context, *RankRequest) (*RankResponse, error)
	mustEmbedUnimplementedRankingServiceServer()
}

// UnimplementedRankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingServiceServer struct{}

func (UnimplementedRankingServiceServer) Rank(context.Context, *RankRequest) (*RankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rank not implemented")
}
func (UnimplementedRankingServiceServer) mustEmbedUnimplementedRankingServiceServer() {}
func (UnimplementedRankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServiceServer will
// result in compilation errors.
type UnsafeRankingServiceServer interface {
	mustEmbedUnimplementedRankingServiceServer()
}

func RegisterRankingServiceServer(s grpc.ServiceRegistrar, srv RankingServiceServer) {
	// If the following call panics, it indicates UnimplementedRankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingService_ServiceDesc, srv)
}

func _RankingService_Rank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).Rank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_Rank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).Rank(ctx, req.(*RankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingService_ServiceDesc is the grpc.ServiceDesc for RankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.ranking.v1.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rank",
			Handler:    _RankingService_Rank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}
