# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PostCreatedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PostCreatedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPostCreatedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PostCreatedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PostCreatedEvent
    def PostId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PostCreatedEvent
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PostCreatedEvent
    def MediaUrl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PostCreatedEvent
    def MediaType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PostCreatedEvent
    def Caption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PostCreatedEvent
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PostCreatedEventStart(builder):
    builder.StartObject(6)

def Start(builder):
    PostCreatedEventStart(builder)

def PostCreatedEventAddPostId(builder, postId):
    builder.PrependUint64Slot(0, postId, 0)

def AddPostId(builder, postId):
    PostCreatedEventAddPostId(builder, postId)

def PostCreatedEventAddUserId(builder, userId):
    builder.PrependUint64Slot(1, userId, 0)

def AddUserId(builder, userId):
    PostCreatedEventAddUserId(builder, userId)

def PostCreatedEventAddMediaUrl(builder, mediaUrl):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(mediaUrl), 0)

def AddMediaUrl(builder, mediaUrl):
    PostCreatedEventAddMediaUrl(builder, mediaUrl)

def PostCreatedEventAddMediaType(builder, mediaType):
    builder.PrependInt8Slot(3, mediaType, 0)

def AddMediaType(builder, mediaType):
    PostCreatedEventAddMediaType(builder, mediaType)

def PostCreatedEventAddCaption(builder, caption):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(caption), 0)

def AddCaption(builder, caption):
    PostCreatedEventAddCaption(builder, caption)

def PostCreatedEventAddCreatedAt(builder, createdAt):
    builder.PrependUint64Slot(5, createdAt, 0)

def AddCreatedAt(builder, createdAt):
    PostCreatedEventAddCreatedAt(builder, createdAt)

def PostCreatedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return PostCreatedEventEnd(builder)
