// automatically generated by the FlatBuffers compiler, do not modify

package feed.events;

@SuppressWarnings("unused")
public final class MediaType {
  private MediaType() { }
  public static final byte Unspecified = 0;
  public static final byte Image = 1;
  public static final byte Video = 2;
  public static final byte Carousel = 3;

  public static final String[] names = { "Unspecified", "Image", "Video", "Carousel", };

  public static String name(int e) { return names[e]; }
}

