// automatically generated by the FlatBuffers compiler, do not modify

package feed.events;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PostCreatedEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PostCreatedEvent getRootAsPostCreatedEvent(ByteBuffer _bb) { return getRootAsPostCreatedEvent(_bb, new PostCreatedEvent()); }
  public static PostCreatedEvent getRootAsPostCreatedEvent(ByteBuffer _bb, PostCreatedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PostCreatedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long postId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long userId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String mediaUrl() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mediaUrlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer mediaUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public byte mediaType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String caption() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer captionAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer captionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public long createdAt() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createPostCreatedEvent(FlatBufferBuilder builder,
      long postId,
      long userId,
      int mediaUrlOffset,
      byte mediaType,
      int captionOffset,
      long createdAt) {
    builder.startTable(6);
    PostCreatedEvent.addCreatedAt(builder, createdAt);
    PostCreatedEvent.addUserId(builder, userId);
    PostCreatedEvent.addPostId(builder, postId);
    PostCreatedEvent.addCaption(builder, captionOffset);
    PostCreatedEvent.addMediaUrl(builder, mediaUrlOffset);
    PostCreatedEvent.addMediaType(builder, mediaType);
    return PostCreatedEvent.endPostCreatedEvent(builder);
  }

  public static void startPostCreatedEvent(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addPostId(FlatBufferBuilder builder, long postId) { builder.addLong(0, postId, 0L); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(1, userId, 0L); }
  public static void addMediaUrl(FlatBufferBuilder builder, int mediaUrlOffset) { builder.addOffset(2, mediaUrlOffset, 0); }
  public static void addMediaType(FlatBufferBuilder builder, byte mediaType) { builder.addByte(3, mediaType, 0); }
  public static void addCaption(FlatBufferBuilder builder, int captionOffset) { builder.addOffset(4, captionOffset, 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, long createdAt) { builder.addLong(5, createdAt, 0L); }
  public static int endPostCreatedEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishPostCreatedEventBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPostCreatedEventBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PostCreatedEvent get(int j) { return get(new PostCreatedEvent(), j); }
    public PostCreatedEvent get(PostCreatedEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

