// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ranking

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CandidateList struct {
	_tab flatbuffers.Table
}

func GetRootAsCandidateList(buf []byte, offset flatbuffers.UOffsetT) *CandidateList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CandidateList{}
	x.Init(buf, n+offset)
	return x
}

func FinishCandidateListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCandidateList(buf []byte, offset flatbuffers.UOffsetT) *CandidateList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CandidateList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCandidateListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CandidateList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CandidateList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CandidateList) Items(obj *Candidate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CandidateList) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CandidateListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CandidateListAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(items), 0)
}
func CandidateListStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CandidateListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
