// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ranking

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Candidate struct {
	_tab flatbuffers.Table
}

func GetRootAsCandidate(buf []byte, offset flatbuffers.UOffsetT) *Candidate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Candidate{}
	x.Init(buf, n+offset)
	return x
}

func FinishCandidateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCandidate(buf []byte, offset flatbuffers.UOffsetT) *Candidate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Candidate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCandidateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Candidate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Candidate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Candidate) PostId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Candidate) MutatePostId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Candidate) AuthorId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Candidate) MutateAuthorId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Candidate) Source() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Candidate) LikeCount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Candidate) MutateLikeCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *Candidate) CommentCount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Candidate) MutateCommentCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *Candidate) CreatedAt() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Candidate) MutateCreatedAt(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func CandidateStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func CandidateAddPostId(builder *flatbuffers.Builder, postId uint64) {
	builder.PrependUint64Slot(0, postId, 0)
}
func CandidateAddAuthorId(builder *flatbuffers.Builder, authorId uint64) {
	builder.PrependUint64Slot(1, authorId, 0)
}
func CandidateAddSource(builder *flatbuffers.Builder, source flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(source), 0)
}
func CandidateAddLikeCount(builder *flatbuffers.Builder, likeCount int64) {
	builder.PrependInt64Slot(3, likeCount, 0)
}
func CandidateAddCommentCount(builder *flatbuffers.Builder, commentCount int64) {
	builder.PrependInt64Slot(4, commentCount, 0)
}
func CandidateAddCreatedAt(builder *flatbuffers.Builder, createdAt uint64) {
	builder.PrependUint64Slot(5, createdAt, 0)
}
func CandidateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
