// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ranking

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RankedList struct {
	_tab flatbuffers.Table
}

func GetRootAsRankedList(buf []byte, offset flatbuffers.UOffsetT) *RankedList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RankedList{}
	x.Init(buf, n+offset)
	return x
}

func FinishRankedListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRankedList(buf []byte, offset flatbuffers.UOffsetT) *RankedList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RankedList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRankedListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RankedList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RankedList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RankedList) Items(obj *RankedItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RankedList) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RankedListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RankedListAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(items), 0)
}
func RankedListStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RankedListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
