// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ranking

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RankedItem struct {
	_tab flatbuffers.Table
}

func GetRootAsRankedItem(buf []byte, offset flatbuffers.UOffsetT) *RankedItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RankedItem{}
	x.Init(buf, n+offset)
	return x
}

func FinishRankedItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRankedItem(buf []byte, offset flatbuffers.UOffsetT) *RankedItem {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RankedItem{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRankedItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RankedItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RankedItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RankedItem) PostId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RankedItem) MutatePostId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *RankedItem) AuthorId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RankedItem) MutateAuthorId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *RankedItem) Source() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RankedItem) Score() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutateScore(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *RankedItem) PLike() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutatePLike(n float64) bool {
	return rcv._tab.MutateFloat64Slot(12, n)
}

func (rcv *RankedItem) PComment() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutatePComment(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func (rcv *RankedItem) PShare() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutatePShare(n float64) bool {
	return rcv._tab.MutateFloat64Slot(16, n)
}

func (rcv *RankedItem) PDwell() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutatePDwell(n float64) bool {
	return rcv._tab.MutateFloat64Slot(18, n)
}

func (rcv *RankedItem) PHide() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RankedItem) MutatePHide(n float64) bool {
	return rcv._tab.MutateFloat64Slot(20, n)
}

func RankedItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func RankedItemAddPostId(builder *flatbuffers.Builder, postId uint64) {
	builder.PrependUint64Slot(0, postId, 0)
}
func RankedItemAddAuthorId(builder *flatbuffers.Builder, authorId uint64) {
	builder.PrependUint64Slot(1, authorId, 0)
}
func RankedItemAddSource(builder *flatbuffers.Builder, source flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(source), 0)
}
func RankedItemAddScore(builder *flatbuffers.Builder, score float64) {
	builder.PrependFloat64Slot(3, score, 0.0)
}
func RankedItemAddPLike(builder *flatbuffers.Builder, pLike float64) {
	builder.PrependFloat64Slot(4, pLike, 0.0)
}
func RankedItemAddPComment(builder *flatbuffers.Builder, pComment float64) {
	builder.PrependFloat64Slot(5, pComment, 0.0)
}
func RankedItemAddPShare(builder *flatbuffers.Builder, pShare float64) {
	builder.PrependFloat64Slot(6, pShare, 0.0)
}
func RankedItemAddPDwell(builder *flatbuffers.Builder, pDwell float64) {
	builder.PrependFloat64Slot(7, pDwell, 0.0)
}
func RankedItemAddPHide(builder *flatbuffers.Builder, pHide float64) {
	builder.PrependFloat64Slot(8, pHide, 0.0)
}
func RankedItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
