#!/usr/bin/env bash
# Regenerates every language's bindings from schemas/proto/*.proto and
# schemas/fbs/*.fbs, and commits the result -- there is no protoc/flatc
# invocation anywhere in a Dockerfile, on purpose (see doc/wire-protocols.md
# for the reasoning). This script is a dev-loop tool, like go/cargo/mvn
# already are: running the system only needs Docker, but changing a schema
# needs this script re-run once, same as any other codegen step.
#
# Split by language, not by schema type:
#  - Go protobuf (protoc-gen-go/protoc-gen-go-grpc) and FlatBuffers for
#    every language (Go/Java/Python/TypeScript/Rust) are generated here
#    and committed.
#  - Java's cold_tier.proto gRPC stubs are generated by Maven's
#    protobuf-maven-plugin at `mvn generate-sources` time instead --
#    fanout-worker's own build already resolves the right
#    protoc-gen-grpc-java native plugin per platform via os-maven-plugin,
#    so duplicating that here would mean vendoring a second native binary
#    just for this script.
#  - Rust's ranking.proto gRPC stubs are generated by tonic-build in
#    ranking-service/build.rs at `cargo build` time -- idiomatic Rust,
#    and the codegen is a pure-Rust build-dependency, not a separate binary.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/env.sh"

command -v protoc >/dev/null || { echo "protoc not found on PATH -- see scripts/env.sh"; exit 1; }
command -v flatc >/dev/null || { echo "flatc not found on PATH -- see scripts/env.sh"; exit 1; }
command -v protoc-gen-go >/dev/null || { echo "protoc-gen-go not found (go install google.golang.org/protobuf/cmd/protoc-gen-go@latest)"; exit 1; }
command -v protoc-gen-go-grpc >/dev/null || { echo "protoc-gen-go-grpc not found (go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest)"; exit 1; }

cd "$ROOT"

echo "==> protobuf: cold_tier.proto -> Go (feed-aggregation-service, server)"
rm -rf services/feed-aggregation-service/internal/genproto/coldtier
mkdir -p services/feed-aggregation-service/internal/genproto/coldtier
protoc -I schemas/proto \
  --go_out=services/feed-aggregation-service/internal/genproto/coldtier --go_opt=paths=source_relative \
  --go-grpc_out=services/feed-aggregation-service/internal/genproto/coldtier --go-grpc_opt=paths=source_relative \
  schemas/proto/cold_tier.proto

echo "==> protobuf: ranking.proto -> Go (feed-aggregation-service, client)"
rm -rf services/feed-aggregation-service/internal/genproto/ranking
mkdir -p services/feed-aggregation-service/internal/genproto/ranking
protoc -I schemas/proto \
  --go_out=services/feed-aggregation-service/internal/genproto/ranking --go_opt=paths=source_relative \
  --go-grpc_out=services/feed-aggregation-service/internal/genproto/ranking --go-grpc_opt=paths=source_relative \
  schemas/proto/ranking.proto

echo "==> FlatBuffers: post_created.fbs -> Go (post-ingestion-service, producer)"
rm -rf services/post-ingestion-service/internal/genfbs
mkdir -p services/post-ingestion-service/internal/genfbs
flatc --go -o services/post-ingestion-service/internal/genfbs schemas/fbs/post_created.fbs

echo "==> FlatBuffers: post_created.fbs -> Java (fanout-worker, consumer)"
rm -rf services/fanout-worker/src/main/java/feed
flatc --java -o services/fanout-worker/src/main/java schemas/fbs/post_created.fbs

echo "==> FlatBuffers: post_created.fbs -> Python (vector-pipeline, consumer)"
rm -rf services/vector-pipeline/genfbs
mkdir -p services/vector-pipeline/genfbs
flatc --python -o services/vector-pipeline/genfbs schemas/fbs/post_created.fbs

echo "==> FlatBuffers: post_created.fbs -> TypeScript (notification-service, consumer)"
rm -rf services/notification-service/src/genfbs
mkdir -p services/notification-service/src/genfbs
flatc --ts -o services/notification-service/src/genfbs schemas/fbs/post_created.fbs

echo "==> FlatBuffers: ranking.fbs -> Go (feed-aggregation-service, client)"
rm -rf services/feed-aggregation-service/internal/genfbs
mkdir -p services/feed-aggregation-service/internal/genfbs
flatc --go -o services/feed-aggregation-service/internal/genfbs schemas/fbs/ranking.fbs

echo "==> FlatBuffers: ranking.fbs -> Rust (ranking-service, server)"
rm -rf services/ranking-service/src/genfbs
mkdir -p services/ranking-service/src/genfbs
flatc --rust -o services/ranking-service/src/genfbs schemas/fbs/ranking.fbs

echo
echo "Done. Java's cold_tier gRPC stubs (mvn generate-sources) and Rust's"
echo "ranking gRPC stubs (cargo build via build.rs) regenerate at their"
echo "own build time, not by this script."
