// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

import "strconv"

type MediaType int8

const (
	MediaTypeUnspecified MediaType = 0
	MediaTypeImage       MediaType = 1
	MediaTypeVideo       MediaType = 2
	MediaTypeCarousel    MediaType = 3
)

var EnumNamesMediaType = map[MediaType]string{
	MediaTypeUnspecified: "Unspecified",
	MediaTypeImage:       "Image",
	MediaTypeVideo:       "Video",
	MediaTypeCarousel:    "Carousel",
}

var EnumValuesMediaType = map[string]MediaType{
	"Unspecified": MediaTypeUnspecified,
	"Image":       MediaTypeImage,
	"Video":       MediaTypeVideo,
	"Carousel":    MediaTypeCarousel,
}

func (v MediaType) String() string {
	if s, ok := EnumNamesMediaType[v]; ok {
		return s
	}
	return "MediaType(" + strconv.FormatInt(int64(v), 10) + ")"
}
