// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PostCreatedEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsPostCreatedEvent(buf []byte, offset flatbuffers.UOffsetT) *PostCreatedEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PostCreatedEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishPostCreatedEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPostCreatedEvent(buf []byte, offset flatbuffers.UOffsetT) *PostCreatedEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PostCreatedEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPostCreatedEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PostCreatedEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PostCreatedEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PostCreatedEvent) PostId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostCreatedEvent) MutatePostId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PostCreatedEvent) UserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostCreatedEvent) MutateUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *PostCreatedEvent) MediaUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PostCreatedEvent) MediaType() MediaType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return MediaType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PostCreatedEvent) MutateMediaType(n MediaType) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *PostCreatedEvent) Caption() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PostCreatedEvent) CreatedAt() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PostCreatedEvent) MutateCreatedAt(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func PostCreatedEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func PostCreatedEventAddPostId(builder *flatbuffers.Builder, postId uint64) {
	builder.PrependUint64Slot(0, postId, 0)
}
func PostCreatedEventAddUserId(builder *flatbuffers.Builder, userId uint64) {
	builder.PrependUint64Slot(1, userId, 0)
}
func PostCreatedEventAddMediaUrl(builder *flatbuffers.Builder, mediaUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(mediaUrl), 0)
}
func PostCreatedEventAddMediaType(builder *flatbuffers.Builder, mediaType MediaType) {
	builder.PrependInt8Slot(3, int8(mediaType), 0)
}
func PostCreatedEventAddCaption(builder *flatbuffers.Builder, caption flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(caption), 0)
}
func PostCreatedEventAddCreatedAt(builder *flatbuffers.Builder, createdAt uint64) {
	builder.PrependUint64Slot(5, createdAt, 0)
}
func PostCreatedEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
