// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MediaType {
  Unspecified = 0,
  Image = 1,
  Video = 2,
  Carousel = 3
}
