// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MediaType } from '../../feed/events/media-type.js';


export class PostCreatedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostCreatedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostCreatedEvent(bb:flatbuffers.ByteBuffer, obj?:PostCreatedEvent):PostCreatedEvent {
  return (obj || new PostCreatedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostCreatedEvent(bb:flatbuffers.ByteBuffer, obj?:PostCreatedEvent):PostCreatedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostCreatedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

postId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

mediaUrl():string|null
mediaUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mediaUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mediaType():MediaType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MediaType.Unspecified;
}

caption():string|null
caption(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
caption(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startPostCreatedEvent(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addPostId(builder:flatbuffers.Builder, postId:bigint) {
  builder.addFieldInt64(0, postId, BigInt('0'));
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(1, userId, BigInt('0'));
}

static addMediaUrl(builder:flatbuffers.Builder, mediaUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, mediaUrlOffset, 0);
}

static addMediaType(builder:flatbuffers.Builder, mediaType:MediaType) {
  builder.addFieldInt8(3, mediaType, MediaType.Unspecified);
}

static addCaption(builder:flatbuffers.Builder, captionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, captionOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAt:bigint) {
  builder.addFieldInt64(5, createdAt, BigInt('0'));
}

static endPostCreatedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPostCreatedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPostCreatedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createPostCreatedEvent(builder:flatbuffers.Builder, postId:bigint, userId:bigint, mediaUrlOffset:flatbuffers.Offset, mediaType:MediaType, captionOffset:flatbuffers.Offset, createdAt:bigint):flatbuffers.Offset {
  PostCreatedEvent.startPostCreatedEvent(builder);
  PostCreatedEvent.addPostId(builder, postId);
  PostCreatedEvent.addUserId(builder, userId);
  PostCreatedEvent.addMediaUrl(builder, mediaUrlOffset);
  PostCreatedEvent.addMediaType(builder, mediaType);
  PostCreatedEvent.addCaption(builder, captionOffset);
  PostCreatedEvent.addCreatedAt(builder, createdAt);
  return PostCreatedEvent.endPostCreatedEvent(builder);
}
}
