// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod feed {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod ranking {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum CandidateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Candidate<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Candidate<'a> {
  type Inner = Candidate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Candidate<'a> {
  pub const VT_POST_ID: flatbuffers::VOffsetT = 4;
  pub const VT_AUTHOR_ID: flatbuffers::VOffsetT = 6;
  pub const VT_SOURCE: flatbuffers::VOffsetT = 8;
  pub const VT_LIKE_COUNT: flatbuffers::VOffsetT = 10;
  pub const VT_COMMENT_COUNT: flatbuffers::VOffsetT = 12;
  pub const VT_CREATED_AT: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Candidate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CandidateArgs<'args>
  ) -> flatbuffers::WIPOffset<Candidate<'bldr>> {
    let mut builder = CandidateBuilder::new(_fbb);
    builder.add_created_at(args.created_at);
    builder.add_comment_count(args.comment_count);
    builder.add_like_count(args.like_count);
    builder.add_author_id(args.author_id);
    builder.add_post_id(args.post_id);
    if let Some(x) = args.source { builder.add_source(x); }
    builder.finish()
  }


  #[inline]
  pub fn post_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Candidate::VT_POST_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn author_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Candidate::VT_AUTHOR_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Candidate::VT_SOURCE, None)}
  }
  #[inline]
  pub fn like_count(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Candidate::VT_LIKE_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn comment_count(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Candidate::VT_COMMENT_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn created_at(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Candidate::VT_CREATED_AT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Candidate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("post_id", Self::VT_POST_ID, false)?
     .visit_field::<u64>("author_id", Self::VT_AUTHOR_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<i64>("like_count", Self::VT_LIKE_COUNT, false)?
     .visit_field::<i64>("comment_count", Self::VT_COMMENT_COUNT, false)?
     .visit_field::<u64>("created_at", Self::VT_CREATED_AT, false)?
     .finish();
    Ok(())
  }
}
pub struct CandidateArgs<'a> {
    pub post_id: u64,
    pub author_id: u64,
    pub source: Option<flatbuffers::WIPOffset<&'a str>>,
    pub like_count: i64,
    pub comment_count: i64,
    pub created_at: u64,
}
impl<'a> Default for CandidateArgs<'a> {
  #[inline]
  fn default() -> Self {
    CandidateArgs {
      post_id: 0,
      author_id: 0,
      source: None,
      like_count: 0,
      comment_count: 0,
      created_at: 0,
    }
  }
}

pub struct CandidateBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CandidateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_post_id(&mut self, post_id: u64) {
    self.fbb_.push_slot::<u64>(Candidate::VT_POST_ID, post_id, 0);
  }
  #[inline]
  pub fn add_author_id(&mut self, author_id: u64) {
    self.fbb_.push_slot::<u64>(Candidate::VT_AUTHOR_ID, author_id, 0);
  }
  #[inline]
  pub fn add_source(&mut self, source: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Candidate::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_like_count(&mut self, like_count: i64) {
    self.fbb_.push_slot::<i64>(Candidate::VT_LIKE_COUNT, like_count, 0);
  }
  #[inline]
  pub fn add_comment_count(&mut self, comment_count: i64) {
    self.fbb_.push_slot::<i64>(Candidate::VT_COMMENT_COUNT, comment_count, 0);
  }
  #[inline]
  pub fn add_created_at(&mut self, created_at: u64) {
    self.fbb_.push_slot::<u64>(Candidate::VT_CREATED_AT, created_at, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CandidateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CandidateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Candidate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Candidate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Candidate");
      ds.field("post_id", &self.post_id());
      ds.field("author_id", &self.author_id());
      ds.field("source", &self.source());
      ds.field("like_count", &self.like_count());
      ds.field("comment_count", &self.comment_count());
      ds.field("created_at", &self.created_at());
      ds.finish()
  }
}
pub enum CandidateListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CandidateList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CandidateList<'a> {
  type Inner = CandidateList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CandidateList<'a> {
  pub const VT_ITEMS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CandidateList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CandidateListArgs<'args>
  ) -> flatbuffers::WIPOffset<CandidateList<'bldr>> {
    let mut builder = CandidateListBuilder::new(_fbb);
    if let Some(x) = args.items { builder.add_items(x); }
    builder.finish()
  }


  #[inline]
  pub fn items(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candidate<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candidate>>>>(CandidateList::VT_ITEMS, None)}
  }
}

impl flatbuffers::Verifiable for CandidateList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Candidate>>>>("items", Self::VT_ITEMS, false)?
     .finish();
    Ok(())
  }
}
pub struct CandidateListArgs<'a> {
    pub items: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Candidate<'a>>>>>,
}
impl<'a> Default for CandidateListArgs<'a> {
  #[inline]
  fn default() -> Self {
    CandidateListArgs {
      items: None,
    }
  }
}

pub struct CandidateListBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CandidateListBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_items(&mut self, items: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Candidate<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CandidateList::VT_ITEMS, items);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CandidateListBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CandidateListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CandidateList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CandidateList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CandidateList");
      ds.field("items", &self.items());
      ds.finish()
  }
}
pub enum RankedItemOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RankedItem<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RankedItem<'a> {
  type Inner = RankedItem<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RankedItem<'a> {
  pub const VT_POST_ID: flatbuffers::VOffsetT = 4;
  pub const VT_AUTHOR_ID: flatbuffers::VOffsetT = 6;
  pub const VT_SOURCE: flatbuffers::VOffsetT = 8;
  pub const VT_SCORE: flatbuffers::VOffsetT = 10;
  pub const VT_P_LIKE: flatbuffers::VOffsetT = 12;
  pub const VT_P_COMMENT: flatbuffers::VOffsetT = 14;
  pub const VT_P_SHARE: flatbuffers::VOffsetT = 16;
  pub const VT_P_DWELL: flatbuffers::VOffsetT = 18;
  pub const VT_P_HIDE: flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RankedItem { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RankedItemArgs<'args>
  ) -> flatbuffers::WIPOffset<RankedItem<'bldr>> {
    let mut builder = RankedItemBuilder::new(_fbb);
    builder.add_p_hide(args.p_hide);
    builder.add_p_dwell(args.p_dwell);
    builder.add_p_share(args.p_share);
    builder.add_p_comment(args.p_comment);
    builder.add_p_like(args.p_like);
    builder.add_score(args.score);
    builder.add_author_id(args.author_id);
    builder.add_post_id(args.post_id);
    if let Some(x) = args.source { builder.add_source(x); }
    builder.finish()
  }


  #[inline]
  pub fn post_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RankedItem::VT_POST_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn author_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RankedItem::VT_AUTHOR_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RankedItem::VT_SOURCE, None)}
  }
  #[inline]
  pub fn score(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_SCORE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn p_like(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_P_LIKE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn p_comment(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_P_COMMENT, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn p_share(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_P_SHARE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn p_dwell(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_P_DWELL, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn p_hide(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(RankedItem::VT_P_HIDE, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RankedItem<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("post_id", Self::VT_POST_ID, false)?
     .visit_field::<u64>("author_id", Self::VT_AUTHOR_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<f64>("score", Self::VT_SCORE, false)?
     .visit_field::<f64>("p_like", Self::VT_P_LIKE, false)?
     .visit_field::<f64>("p_comment", Self::VT_P_COMMENT, false)?
     .visit_field::<f64>("p_share", Self::VT_P_SHARE, false)?
     .visit_field::<f64>("p_dwell", Self::VT_P_DWELL, false)?
     .visit_field::<f64>("p_hide", Self::VT_P_HIDE, false)?
     .finish();
    Ok(())
  }
}
pub struct RankedItemArgs<'a> {
    pub post_id: u64,
    pub author_id: u64,
    pub source: Option<flatbuffers::WIPOffset<&'a str>>,
    pub score: f64,
    pub p_like: f64,
    pub p_comment: f64,
    pub p_share: f64,
    pub p_dwell: f64,
    pub p_hide: f64,
}
impl<'a> Default for RankedItemArgs<'a> {
  #[inline]
  fn default() -> Self {
    RankedItemArgs {
      post_id: 0,
      author_id: 0,
      source: None,
      score: 0.0,
      p_like: 0.0,
      p_comment: 0.0,
      p_share: 0.0,
      p_dwell: 0.0,
      p_hide: 0.0,
    }
  }
}

pub struct RankedItemBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RankedItemBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_post_id(&mut self, post_id: u64) {
    self.fbb_.push_slot::<u64>(RankedItem::VT_POST_ID, post_id, 0);
  }
  #[inline]
  pub fn add_author_id(&mut self, author_id: u64) {
    self.fbb_.push_slot::<u64>(RankedItem::VT_AUTHOR_ID, author_id, 0);
  }
  #[inline]
  pub fn add_source(&mut self, source: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RankedItem::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_score(&mut self, score: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_SCORE, score, 0.0);
  }
  #[inline]
  pub fn add_p_like(&mut self, p_like: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_P_LIKE, p_like, 0.0);
  }
  #[inline]
  pub fn add_p_comment(&mut self, p_comment: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_P_COMMENT, p_comment, 0.0);
  }
  #[inline]
  pub fn add_p_share(&mut self, p_share: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_P_SHARE, p_share, 0.0);
  }
  #[inline]
  pub fn add_p_dwell(&mut self, p_dwell: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_P_DWELL, p_dwell, 0.0);
  }
  #[inline]
  pub fn add_p_hide(&mut self, p_hide: f64) {
    self.fbb_.push_slot::<f64>(RankedItem::VT_P_HIDE, p_hide, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RankedItemBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RankedItemBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RankedItem<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RankedItem<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RankedItem");
      ds.field("post_id", &self.post_id());
      ds.field("author_id", &self.author_id());
      ds.field("source", &self.source());
      ds.field("score", &self.score());
      ds.field("p_like", &self.p_like());
      ds.field("p_comment", &self.p_comment());
      ds.field("p_share", &self.p_share());
      ds.field("p_dwell", &self.p_dwell());
      ds.field("p_hide", &self.p_hide());
      ds.finish()
  }
}
pub enum RankedListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RankedList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RankedList<'a> {
  type Inner = RankedList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RankedList<'a> {
  pub const VT_ITEMS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RankedList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RankedListArgs<'args>
  ) -> flatbuffers::WIPOffset<RankedList<'bldr>> {
    let mut builder = RankedListBuilder::new(_fbb);
    if let Some(x) = args.items { builder.add_items(x); }
    builder.finish()
  }


  #[inline]
  pub fn items(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RankedItem<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RankedItem>>>>(RankedList::VT_ITEMS, None)}
  }
}

impl flatbuffers::Verifiable for RankedList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<RankedItem>>>>("items", Self::VT_ITEMS, false)?
     .finish();
    Ok(())
  }
}
pub struct RankedListArgs<'a> {
    pub items: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RankedItem<'a>>>>>,
}
impl<'a> Default for RankedListArgs<'a> {
  #[inline]
  fn default() -> Self {
    RankedListArgs {
      items: None,
    }
  }
}

pub struct RankedListBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RankedListBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_items(&mut self, items: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<RankedItem<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RankedList::VT_ITEMS, items);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RankedListBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RankedListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RankedList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RankedList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RankedList");
      ds.field("items", &self.items());
      ds.finish()
  }
}
}  // pub mod ranking
}  // pub mod feed

