// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: cold_tier.proto

// ColdTierService: fanout-worker (Java) -> feed-aggregation-service (Go).
// Appends a dormant follower's fan-out entry into the BadgerDB cold tier.
// Internal, service-to-service only -- bypasses the Envoy gateway entirely
// (see doc/gateway.md). Fire-and-forget on the caller's side: a failed
// append is logged and dropped, never retried (an accepted loss for
// dormant users, per doc/caching.md).

package coldtierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ColdTierService_Append_FullMethodName = "/feed.coldtier.v1.ColdTierService/Append"
)

// ColdTierServiceClient is the client API for ColdTierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColdTierServiceClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
}

type coldTierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColdTierServiceClient(cc grpc.ClientConnInterface) ColdTierServiceClient {
	return &coldTierServiceClient{cc}
}

func (c *coldTierServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, ColdTierService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColdTierServiceServer is the server API for ColdTierService service.
// All implementations must embed UnimplementedColdTierServiceServer
// for forward compatibility.
type ColdTierServiceServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	mustEmbedUnimplementedColdTierServiceServer()
}

// UnimplementedColdTierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedColdTierServiceServer struct{}

func (UnimplementedColdTierServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedColdTierServiceServer) mustEmbedUnimplementedColdTierServiceServer() {}
func (UnimplementedColdTierServiceServer) testEmbeddedByValue()                         {}

// UnsafeColdTierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColdTierServiceServer will
// result in compilation errors.
type UnsafeColdTierServiceServer interface {
	mustEmbedUnimplementedColdTierServiceServer()
}

func RegisterColdTierServiceServer(s grpc.ServiceRegistrar, srv ColdTierServiceServer) {
	// If the following call panics, it indicates UnimplementedColdTierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ColdTierService_ServiceDesc, srv)
}

func _ColdTierService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColdTierServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColdTierService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColdTierServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ColdTierService_ServiceDesc is the grpc.ServiceDesc for ColdTierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColdTierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.coldtier.v1.ColdTierService",
	HandlerType: (*ColdTierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _ColdTierService_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cold_tier.proto",
}
