// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: cold_tier.proto

// ColdTierService: fanout-worker (Java) -> feed-aggregation-service (Go).
// Appends a dormant follower's fan-out entry into the BadgerDB cold tier.
// Internal, service-to-service only -- bypasses the Envoy gateway entirely
// (see doc/gateway.md). Fire-and-forget on the caller's side: a failed
// append is logged and dropped, never retried (an accepted loss for
// dormant users, per doc/caching.md).

package coldtierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      uint64                 `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_cold_tier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cold_tier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_cold_tier_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AppendRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AppendRequest) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appended      bool                   `protobuf:"varint,1,opt,name=appended,proto3" json:"appended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_cold_tier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cold_tier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_cold_tier_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetAppended() bool {
	if x != nil {
		return x.Appended
	}
	return false
}

var File_cold_tier_proto protoreflect.FileDescriptor

const file_cold_tier_proto_rawDesc = "" +
	"\n" +
	"\x0fcold_tier.proto\x12\x10feed.coldtier.v1\"^\n" +
	"\rAppendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x04R\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x04R\bauthorId\",\n" +
	"\x0eAppendResponse\x12\x1a\n" +
	"\bappended\x18\x01 \x01(\bR\bappended2^\n" +
	"\x0fColdTierService\x12K\n" +
	"\x06Append\x12\x1f.feed.coldtier.v1.AppendRequest\x1a .feed.coldtier.v1.AppendResponseBm\n" +
	"\x1acom.feed.genproto.coldtierB\rColdTierProtoP\x01Z>feed-aggregation-service/internal/genproto/coldtier;coldtierpbb\x06proto3"

var (
	file_cold_tier_proto_rawDescOnce sync.Once
	file_cold_tier_proto_rawDescData []byte
)

func file_cold_tier_proto_rawDescGZIP() []byte {
	file_cold_tier_proto_rawDescOnce.Do(func() {
		file_cold_tier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cold_tier_proto_rawDesc), len(file_cold_tier_proto_rawDesc)))
	})
	return file_cold_tier_proto_rawDescData
}

var file_cold_tier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cold_tier_proto_goTypes = []any{
	(*AppendRequest)(nil),  // 0: feed.coldtier.v1.AppendRequest
	(*AppendResponse)(nil), // 1: feed.coldtier.v1.AppendResponse
}
var file_cold_tier_proto_depIdxs = []int32{
	0, // 0: feed.coldtier.v1.ColdTierService.Append:input_type -> feed.coldtier.v1.AppendRequest
	1, // 1: feed.coldtier.v1.ColdTierService.Append:output_type -> feed.coldtier.v1.AppendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cold_tier_proto_init() }
func file_cold_tier_proto_init() {
	if File_cold_tier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cold_tier_proto_rawDesc), len(file_cold_tier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cold_tier_proto_goTypes,
		DependencyIndexes: file_cold_tier_proto_depIdxs,
		MessageInfos:      file_cold_tier_proto_msgTypes,
	}.Build()
	File_cold_tier_proto = out.File
	file_cold_tier_proto_goTypes = nil
	file_cold_tier_proto_depIdxs = nil
}
